language: python
python: 2.7
env:
- TOXENV=py27
- TOXENV=pypy
install:
- pip install -U tox twine wheel
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapinghub
  password:
    secure: Uys+MPglnS5WMNN98aUU78tAl2HUSRsqLAVRENNe2f9EabPp3sSeSBMU7rw9hinFJO0JU22mNh1hwR42wPv+OA8o/3QSEswS53noGNoK3pQjeByn1rEiRHSqEJdMxH1EmsyH44AR/6EU6NcnybtGLSjhPBdbZFRdDXp+mgO4v2Y=
  on:
    tags: true
    repo: scrapinghub/skinfer
    condition: $TOXENV == py27
