language: python
python: 2.7
env:
- TOXENV=py27
- TOXENV=pypy
install:
- pip install tox
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: eljunior
  password:
    secure: QqknrtagKtsIjvniww4APNjnvolWG6FSmY9ql3OOwKfeW8XA6QQdI/waCBx/TiDkKFBDlC/TYIDJVtsks8kSZQ5i42zJ1MpQtSQx0dqA8vrRQxHh44RoUGaIHB4YvKs1UXH2e2O5coMkhXdU+MHn+GRAvuw9B+v4zoP+NGp4uec=
  on:
    tags: true
    repo: scrapinghub/skinfer
    condition: $TOXENV == py27
